[['textBlock', ''], ['inputBlock', '#!/usr/bin/python\n                 \nimport matplotlib               \n', 1], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 134, in <module>\n    from matplotlib.rcsetup import (defaultParams,\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py", line 18, in <module>\n    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/fontconfig_pattern.py", line 23, in <module>\n    from matplotlib.pyparsing import Literal, ZeroOrMore, \\\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 3207, in <module>\n    _escapedHexChar = Combine( Suppress(_bslash + "0x") + Word(hexnums) ).setParseAction(lambda s,l,t:unichr(int(t[0],16)))\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2923, in __init__\n    self.leaveWhitespace()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2565, in leaveWhitespace\n    self.expr = self.expr.copy()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 681, in copy\n    cpy = copy.copy( self )\n  File "/usr/lib/python2.7/copy.py", line 88, in copy\n    rv = reductor(2)\nTypeError: __call__() takes at most 5 arguments (6 given)\n\n'], ['inputBlock', 'import numpy as np                  \n', 4], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 137, in <module>\n    import add_newdocs\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 9, in <module>\n    from numpy.lib import add_newdoc\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 4, in <module>\n    from type_check import *\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 8, in <module>\n    import numpy.core.numeric as _nx\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 6, in <module>\n    import umath\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\nImportError: numpy.core.multiarray failed to import\n\n'], ['inputBlock', 'from pylab import *\n', 5], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\n  File "/usr/bin/pyreport", line 584, in __call__\n    return self.pylab_import(name, globals, locals, fromlist)\n  File "/usr/bin/pyreport", line 591, in pylab_import\n    matplotlib = self.original_import("matplotlib")\n  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 134, in <module>\n    from matplotlib.rcsetup import (defaultParams,\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py", line 18, in <module>\n    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/fontconfig_pattern.py", line 23, in <module>\n    from matplotlib.pyparsing import Literal, ZeroOrMore, \\\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 3207, in <module>\n    _escapedHexChar = Combine( Suppress(_bslash + "0x") + Word(hexnums) ).setParseAction(lambda s,l,t:unichr(int(t[0],16)))\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2923, in __init__\n    self.leaveWhitespace()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2565, in leaveWhitespace\n    self.expr = self.expr.copy()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 681, in copy\n    cpy = copy.copy( self )\n  File "/usr/lib/python2.7/copy.py", line 88, in copy\n    rv = reductor(2)\nTypeError: __call__() takes at most 5 arguments (6 given)\n\n'], ['inputBlock', 'from matplotlib import pyplot as pl\n#from matplotlib import axis as ax                                  \n                                                                    \n', 6], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 134, in <module>\n    from matplotlib.rcsetup import (defaultParams,\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py", line 18, in <module>\n    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/fontconfig_pattern.py", line 23, in <module>\n    from matplotlib.pyparsing import Literal, ZeroOrMore, \\\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 3207, in <module>\n    _escapedHexChar = Combine( Suppress(_bslash + "0x") + Word(hexnums) ).setParseAction(lambda s,l,t:unichr(int(t[0],16)))\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2923, in __init__\n    self.leaveWhitespace()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2565, in leaveWhitespace\n    self.expr = self.expr.copy()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 681, in copy\n    cpy = copy.copy( self )\n  File "/usr/lib/python2.7/copy.py", line 88, in copy\n    rv = reductor(2)\nTypeError: __call__() takes at most 5 arguments (6 given)\n\n'], ['inputBlock', 'from matplotlib.ticker import MultipleLocator#, FormatStrFormatter\n', 8], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 134, in <module>\n    from matplotlib.rcsetup import (defaultParams,\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py", line 18, in <module>\n    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/fontconfig_pattern.py", line 23, in <module>\n    from matplotlib.pyparsing import Literal, ZeroOrMore, \\\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 3207, in <module>\n    _escapedHexChar = Combine( Suppress(_bslash + "0x") + Word(hexnums) ).setParseAction(lambda s,l,t:unichr(int(t[0],16)))\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2923, in __init__\n    self.leaveWhitespace()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2565, in leaveWhitespace\n    self.expr = self.expr.copy()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 681, in copy\n    cpy = copy.copy( self )\n  File "/usr/lib/python2.7/copy.py", line 88, in copy\n    rv = reductor(2)\nTypeError: __call__() takes at most 5 arguments (6 given)\n\n'], ['inputBlock', "from matplotlib.backends.backend_pdf import PdfPages\n#pp = PdfPages('plots/130729_Hopkins_shifted_df_DF.pdf')                                                        \n                                                                                                                \n", 9], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/__init__.py", line 134, in <module>\n    from matplotlib.rcsetup import (defaultParams,\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/rcsetup.py", line 18, in <module>\n    from matplotlib.fontconfig_pattern import parse_fontconfig_pattern\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/fontconfig_pattern.py", line 23, in <module>\n    from matplotlib.pyparsing import Literal, ZeroOrMore, \\\n  File "/usr/bin/pyreport", line 587, in __call__\n    return self.original_import(name, globals, locals, fromlist)\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 3207, in <module>\n    _escapedHexChar = Combine( Suppress(_bslash + "0x") + Word(hexnums) ).setParseAction(lambda s,l,t:unichr(int(t[0],16)))\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2923, in __init__\n    self.leaveWhitespace()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 2565, in leaveWhitespace\n    self.expr = self.expr.copy()\n  File "/usr/lib/pymodules/python2.7/matplotlib/pyparsing.py", line 681, in copy\n    cpy = copy.copy( self )\n  File "/usr/lib/python2.7/copy.py", line 88, in copy\n    rv = reductor(2)\nTypeError: __call__() takes at most 5 arguments (6 given)\n\n'], ['inputBlock', "\nx_t ,y_t = np.loadtxt('data/CG10e2t.csv',delimiter=',',unpack=True, usecols = [0,1])\n", 12], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 4, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', "x_x ,y_x = np.loadtxt('data/CG10e2x.csv',delimiter=',',unpack=True, usecols = [0,1])\n", 13], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', "x_y ,y_y = np.loadtxt('data/CG10e2y.csv',delimiter=',',unpack=True, usecols = [0,1])\n", 14], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', "x_z ,y_z = np.loadtxt('data/CG10e2z.csv',delimiter=',',unpack=True, usecols = [0,1])\n", 15], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', '\nz_t = np.ma.polyfit(x_t, y_t, 3)#deg, rcond=None, full=False, w=None, cov=False)\n#z_t = np.polynomial.polynomial.polyfit(x_t, y_t,10)#deg, rcond=None, full=False, w=None, cov=False)                                                                                                    \n                                                                                                                                                                                                        \n', 17], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 4, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', 'z_t_fit = np.poly1d(z_t)\n', 19], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', 'x_fit = np.linspace(0,50,50)\n', 20], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', '\nz_z = np.ma.polyfit(x_z, y_z, 5)#deg, rcond=None, full=False, w=None, cov=False)\n', 22], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 4, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', 'z_z_fit = np.poly1d(z_z)\n', 23], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', 'x_fit = np.linspace(0,50,25)\n', 24], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', 'y_interp = np.interp(x_fit, x_t,y_t)\n', 25], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'np\' is not defined\n\n'], ['inputBlock', '\npl.figure()\n', 27], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 4, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.plot(x_t,y_t, label = 'total')\n", 28], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.plot(x_x,y_x, label = r'$\\hat{x}$')\n", 29], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.plot(x_y,y_y, label = r'$\\hat{y}$')\n", 30], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.plot(x_z,y_z, label = r'$\\hat{z}$')\n", 31], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.plot(x_fit,z_t_fit(x_fit), label = r'$t\\, fit$')\n", 32], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.plot(x_fit,y_interp, label = r'$t\\, interp$')\n", 33], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.xlabel(r'$\\hbar\\omega\\,\\,\\,[eV]$', size = 24)\n", 34], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.ylabel(r'$\\varepsilon^{\\prime\\prime}(\\omega)$', size = 24)\n", 35], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', 'pl.legend()\n', 36], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n'], ['inputBlock', "pl.savefig('plots/DNA_spectr_tot_x_y_z.pdf')\n", 37], ['errorBlock', 'Traceback (most recent call last):\n  File "/usr/bin/pyreport", line 477, in __call__\n    exec block_text in self.namespace\n  File "<string>", line 3, in <module>\nNameError: name \'pl\' is not defined\n\n']]